# Site settings
title: Pseudoprime
email: mitchell@pseudopri.me 
description: > # this means to ignore newlines until "baseurl:"
    Mitchell's personal website and build log. An adventure through the creation of use{full/less} things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pseudopri.me" # the base hostname & protocol for your site
twitter_username: pixlheart
github_username: mitch-karch 

# Build settings
markdown: kramdown
